### ISSUE TITLE
breadcrumb link to package broken on channel/edit

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#4]
`Data > Package-Name-Link > You-Are-Here-Channel`

"Package-Name-Link" here points to `packages//edit`

**Comment by dasantonym** [comment]
fixed and pushed

**Comment by fjenett** [comment]
Hm, still not fixed for me after pulling latest version …

http://192.168.56.101:8080/channels/a15be547-88eb-4790-ab6b-7231f329a376/edit

**Comment by dasantonym** [comment]
works for me, right down to the streams. maybe some error during updates on the vm?
